package database

import (
	"github.com/briandenicola/ancient-coins-api/models"
	"gorm.io/gorm"
)

// romanImperialFigureSeedVersionKey / currentRomanImperialFigureSeedVersion follow
// the same idempotent-seed pattern as seedMintLocations.
const romanImperialFigureSeedVersionKey = "RomanImperialFigureSeedVersion"
const currentRomanImperialFigureSeedVersion = "1"

func seedRomanImperialFigures(db *gorm.DB) error {
	var existingSetting models.AppSetting
	err := db.First(&existingSetting, "key = ?", romanImperialFigureSeedVersionKey).Error
	if err == nil && existingSetting.Value == currentRomanImperialFigureSeedVersion {
		return nil
	}
	if err != nil && err != gorm.ErrRecordNotFound {
		return err
	}

	seed := []models.RomanImperialFigure{
		{Name: "Julius Caesar", NormalizedName: "juliuscaesar", Aliases: models.StringList{"Caesar", "Gaius Julius Caesar"}, Role: models.ImperialFigureRoleOther, Region: models.ImperialFigureRegionWest, Dynasty: "Late Republic (precursor)", ReignStart: -49, ReignEnd: -44, SortOrder: 1, RarityTier: models.RarityTierRare, Notes: "Never \"Emperor\" -- Augustus is the traditional first emperor. Included so a coin can be logged against him."},
		{Name: "Augustus", NormalizedName: "augustus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Julio-Claudian", ReignStart: -27, ReignEnd: 14, SortOrder: 2, RarityTier: models.RarityTierCommon},
		{Name: "Tiberius", NormalizedName: "tiberius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Julio-Claudian", ReignStart: 14, ReignEnd: 37, SortOrder: 3, RarityTier: models.RarityTierCommon},
		{Name: "Caligula", NormalizedName: "caligula", Aliases: models.StringList{"Gaius"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Julio-Claudian", ReignStart: 37, ReignEnd: 41, SortOrder: 4, RarityTier: models.RarityTierScarce, Notes: "Also known as Gaius."},
		{Name: "Claudius", NormalizedName: "claudius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Julio-Claudian", ReignStart: 41, ReignEnd: 54, SortOrder: 5, RarityTier: models.RarityTierCommon},
		{Name: "Nero", NormalizedName: "nero", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Julio-Claudian", ReignStart: 54, ReignEnd: 68, SortOrder: 6, RarityTier: models.RarityTierCommon},
		{Name: "Galba", NormalizedName: "galba", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Four Emperors", ReignStart: 68, ReignEnd: 69, SortOrder: 7, RarityTier: models.RarityTierScarce},
		{Name: "Otho", NormalizedName: "otho", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Four Emperors", ReignStart: 69, ReignEnd: 69, SortOrder: 8, RarityTier: models.RarityTierRare, Notes: "Mostly Rome-mint denarii; no provincial bronze."},
		{Name: "Vitellius", NormalizedName: "vitellius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Four Emperors", ReignStart: 69, ReignEnd: 69, SortOrder: 9, RarityTier: models.RarityTierScarce},
		{Name: "Vespasian", NormalizedName: "vespasian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Flavian", ReignStart: 69, ReignEnd: 79, SortOrder: 10, RarityTier: models.RarityTierCommon},
		{Name: "Titus", NormalizedName: "titus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Flavian", ReignStart: 79, ReignEnd: 81, SortOrder: 11, RarityTier: models.RarityTierScarce},
		{Name: "Domitian", NormalizedName: "domitian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Flavian", ReignStart: 81, ReignEnd: 96, SortOrder: 12, RarityTier: models.RarityTierCommon},
		{Name: "Nerva", NormalizedName: "nerva", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 96, ReignEnd: 98, SortOrder: 13, RarityTier: models.RarityTierScarce},
		{Name: "Trajan", NormalizedName: "trajan", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 98, ReignEnd: 117, SortOrder: 14, RarityTier: models.RarityTierCommon},
		{Name: "Hadrian", NormalizedName: "hadrian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 117, ReignEnd: 138, SortOrder: 15, RarityTier: models.RarityTierCommon},
		{Name: "Antoninus Pius", NormalizedName: "antoninuspius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 138, ReignEnd: 161, SortOrder: 16, RarityTier: models.RarityTierCommon},
		{Name: "Marcus Aurelius", NormalizedName: "marcusaurelius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 161, ReignEnd: 180, SortOrder: 17, RarityTier: models.RarityTierCommon},
		{Name: "Lucius Verus", NormalizedName: "luciusverus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 161, ReignEnd: 169, SortOrder: 18, RarityTier: models.RarityTierScarce, Notes: "Co-emperor with Marcus Aurelius."},
		{Name: "Commodus", NormalizedName: "commodus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Nerva-Antonine", ReignStart: 177, ReignEnd: 192, SortOrder: 19, RarityTier: models.RarityTierCommon, Notes: "Co-emperor from 177, sole from 180."},
		{Name: "Pertinax", NormalizedName: "pertinax", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Five Emperors", ReignStart: 193, ReignEnd: 193, SortOrder: 20, RarityTier: models.RarityTierRare},
		{Name: "Didius Julianus", NormalizedName: "didiusjulianus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Five Emperors", ReignStart: 193, ReignEnd: 193, SortOrder: 21, RarityTier: models.RarityTierRare},
		{Name: "Pescennius Niger", NormalizedName: "pescenniusniger", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Five Emperors", ReignStart: 193, ReignEnd: 194, SortOrder: 22, RarityTier: models.RarityTierRare, Notes: "Rival claimant in the East, defeated by Severus."},
		{Name: "Clodius Albinus", NormalizedName: "clodiusalbinus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Year of the Five Emperors", ReignStart: 193, ReignEnd: 197, SortOrder: 23, RarityTier: models.RarityTierScarce, Notes: "Rival claimant, Caesar then self-styled Augustus."},
		{Name: "Septimius Severus", NormalizedName: "septimiusseverus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 193, ReignEnd: 211, SortOrder: 24, RarityTier: models.RarityTierCommon},
		{Name: "Caracalla", NormalizedName: "caracalla", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 198, ReignEnd: 217, SortOrder: 25, RarityTier: models.RarityTierCommon, Notes: "Co-emperor from 198, sole from 211."},
		{Name: "Geta", NormalizedName: "geta", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 209, ReignEnd: 211, SortOrder: 26, RarityTier: models.RarityTierScarce, Notes: "Co-emperor, murdered by Caracalla."},
		{Name: "Macrinus", NormalizedName: "macrinus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 217, ReignEnd: 218, SortOrder: 27, RarityTier: models.RarityTierScarce},
		{Name: "Diadumenian", NormalizedName: "diadumenian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 218, ReignEnd: 218, SortOrder: 28, RarityTier: models.RarityTierRare, Notes: "Briefly hailed Augustus by troops just before his death; catalogued mainly as Caesar."},
		{Name: "Elagabalus", NormalizedName: "elagabalus", Aliases: models.StringList{"Heliogabalus"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 218, ReignEnd: 222, SortOrder: 29, RarityTier: models.RarityTierCommon, Notes: "Also known as Heliogabalus."},
		{Name: "Severus Alexander", NormalizedName: "severusalexander", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Severan", ReignStart: 222, ReignEnd: 235, SortOrder: 30, RarityTier: models.RarityTierCommon},
		{Name: "Maximinus Thrax", NormalizedName: "maximinusthrax", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 235, ReignEnd: 238, SortOrder: 31, RarityTier: models.RarityTierScarce},
		{Name: "Gordian I", NormalizedName: "gordiani", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 238, ReignEnd: 238, SortOrder: 32, RarityTier: models.RarityTierVeryRare, Notes: "~3-week reign."},
		{Name: "Gordian II", NormalizedName: "gordianii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 238, ReignEnd: 238, SortOrder: 33, RarityTier: models.RarityTierVeryRare, Notes: "~3-week reign, co-ruled with father."},
		{Name: "Pupienus", NormalizedName: "pupienus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 238, ReignEnd: 238, SortOrder: 34, RarityTier: models.RarityTierScarce},
		{Name: "Balbinus", NormalizedName: "balbinus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 238, ReignEnd: 238, SortOrder: 35, RarityTier: models.RarityTierScarce},
		{Name: "Gordian III", NormalizedName: "gordianiii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 238, ReignEnd: 244, SortOrder: 36, RarityTier: models.RarityTierCommon},
		{Name: "Philip I", NormalizedName: "philipi", Aliases: models.StringList{"Philip the Arab"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 244, ReignEnd: 249, SortOrder: 37, RarityTier: models.RarityTierCommon, Notes: "Known as Philip the Arab."},
		{Name: "Philip II", NormalizedName: "philipii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 247, ReignEnd: 249, SortOrder: 38, RarityTier: models.RarityTierScarce, Notes: "Co-emperor (Caesar 244-247, Augustus 247-249)."},
		{Name: "Trajan Decius", NormalizedName: "trajandecius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 249, ReignEnd: 251, SortOrder: 39, RarityTier: models.RarityTierCommon},
		{Name: "Herennius Etruscus", NormalizedName: "herenniusetruscus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 251, ReignEnd: 251, SortOrder: 40, RarityTier: models.RarityTierScarce, Notes: "Co-emperor, killed alongside his father."},
		{Name: "Hostilian", NormalizedName: "hostilian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 251, ReignEnd: 251, SortOrder: 41, RarityTier: models.RarityTierRare, Notes: "Briefly sole/co-emperor; died of plague within months."},
		{Name: "Trebonianus Gallus", NormalizedName: "trebonianusgallus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 251, ReignEnd: 253, SortOrder: 42, RarityTier: models.RarityTierScarce},
		{Name: "Volusianus", NormalizedName: "volusianus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 251, ReignEnd: 253, SortOrder: 43, RarityTier: models.RarityTierScarce, Notes: "Co-emperor (son of Trebonianus Gallus)."},
		{Name: "Aemilian", NormalizedName: "aemilian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 253, ReignEnd: 253, SortOrder: 44, RarityTier: models.RarityTierRare, Notes: "~3-month reign."},
		{Name: "Valerian", NormalizedName: "valerian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 253, ReignEnd: 260, SortOrder: 45, RarityTier: models.RarityTierCommon},
		{Name: "Gallienus", NormalizedName: "gallienus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 253, ReignEnd: 268, SortOrder: 46, RarityTier: models.RarityTierCommon, Notes: "Co-emperor 253-260, sole 260-268."},
		{Name: "Saloninus", NormalizedName: "saloninus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 260, ReignEnd: 260, SortOrder: 47, RarityTier: models.RarityTierRare, Notes: "Briefly hailed Augustus just before his death; catalogued mainly as Caesar."},
		{Name: "Claudius II Gothicus", NormalizedName: "claudiusiigothicus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 268, ReignEnd: 270, SortOrder: 48, RarityTier: models.RarityTierCommon},
		{Name: "Quintillus", NormalizedName: "quintillus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 270, ReignEnd: 270, SortOrder: 49, RarityTier: models.RarityTierScarce},
		{Name: "Aurelian", NormalizedName: "aurelian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 270, ReignEnd: 275, SortOrder: 50, RarityTier: models.RarityTierCommon},
		{Name: "Tacitus", NormalizedName: "tacitus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 275, ReignEnd: 276, SortOrder: 51, RarityTier: models.RarityTierScarce},
		{Name: "Florian", NormalizedName: "florian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 276, ReignEnd: 276, SortOrder: 52, RarityTier: models.RarityTierScarce},
		{Name: "Probus", NormalizedName: "probus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 276, ReignEnd: 282, SortOrder: 53, RarityTier: models.RarityTierCommon},
		{Name: "Carus", NormalizedName: "carus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 282, ReignEnd: 283, SortOrder: 54, RarityTier: models.RarityTierScarce},
		{Name: "Carinus", NormalizedName: "carinus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 283, ReignEnd: 285, SortOrder: 55, RarityTier: models.RarityTierScarce},
		{Name: "Numerian", NormalizedName: "numerian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Crisis of the Third Century", ReignStart: 283, ReignEnd: 284, SortOrder: 56, RarityTier: models.RarityTierScarce},
		{Name: "Postumus", NormalizedName: "postumus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 260, ReignEnd: 269, SortOrder: 57, RarityTier: models.RarityTierScarce, Notes: "Gallic Empire."},
		{Name: "Laelian", NormalizedName: "laelian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 269, ReignEnd: 269, SortOrder: 58, RarityTier: models.RarityTierVeryRare, Notes: "Gallic Empire, brief."},
		{Name: "Marius", NormalizedName: "marius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 269, ReignEnd: 269, SortOrder: 59, RarityTier: models.RarityTierVeryRare, Notes: "Gallic Empire, reportedly days-long reign."},
		{Name: "Victorinus", NormalizedName: "victorinus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 269, ReignEnd: 271, SortOrder: 60, RarityTier: models.RarityTierScarce, Notes: "Gallic Empire."},
		{Name: "Tetricus I", NormalizedName: "tetricusi", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 271, ReignEnd: 274, SortOrder: 61, RarityTier: models.RarityTierScarce, Notes: "Gallic Empire, last of the line."},
		{Name: "Tetricus II", NormalizedName: "tetricusii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 271, ReignEnd: 274, SortOrder: 62, RarityTier: models.RarityTierScarce, Notes: "Gallic Empire, never sole Augustus."},
		{Name: "Regalianus", NormalizedName: "regalianus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 260, ReignEnd: 260, SortOrder: 63, RarityTier: models.RarityTierVeryRare, Notes: "Brief Illyricum usurper under Gallienus."},
		{Name: "Vabalathus", NormalizedName: "vabalathus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionEast, Dynasty: "Breakaway regimes", ReignStart: 267, ReignEnd: 272, SortOrder: 64, RarityTier: models.RarityTierRare, Notes: "Palmyrene Empire; briefly styled Augustus."},
		{Name: "Zenobia", NormalizedName: "zenobia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionEast, Dynasty: "Breakaway regimes", ReignStart: 267, ReignEnd: 272, SortOrder: 65, RarityTier: models.RarityTierRare, Notes: "Palmyrene regent, styled Augusta."},
		{Name: "Carausius", NormalizedName: "carausius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 286, ReignEnd: 293, SortOrder: 66, RarityTier: models.RarityTierScarce, Notes: "Britannic Empire; comparatively plentiful/popular with collectors."},
		{Name: "Allectus", NormalizedName: "allectus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Breakaway regimes", ReignStart: 293, ReignEnd: 296, SortOrder: 67, RarityTier: models.RarityTierScarce, Notes: "Britannic Empire, succeeded Carausius."},
		{Name: "Diocletian", NormalizedName: "diocletian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 284, ReignEnd: 305, SortOrder: 68, RarityTier: models.RarityTierCommon, Notes: "Senior Augustus; region tagged west per this dataset's pre-395 convention even though based in the East."},
		{Name: "Maximian", NormalizedName: "maximian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 286, ReignEnd: 308, SortOrder: 69, RarityTier: models.RarityTierCommon, Notes: "Reigned 286-305 and again 306-308."},
		{Name: "Constantius I Chlorus", NormalizedName: "constantiusichlorus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 293, ReignEnd: 306, SortOrder: 70, RarityTier: models.RarityTierScarce, Notes: "Caesar 293-305, Augustus 305-306."},
		{Name: "Galerius", NormalizedName: "galerius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 293, ReignEnd: 311, SortOrder: 71, RarityTier: models.RarityTierScarce, Notes: "Caesar 293-305, Augustus 305-311."},
		{Name: "Severus II", NormalizedName: "severusii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 306, ReignEnd: 307, SortOrder: 72, RarityTier: models.RarityTierRare},
		{Name: "Maxentius", NormalizedName: "maxentius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 306, ReignEnd: 312, SortOrder: 73, RarityTier: models.RarityTierScarce, Notes: "Held Rome/Italy against Constantine; not part of the recognized Tetrarchy succession."},
		{Name: "Maximinus Daza", NormalizedName: "maximinusdaza", Aliases: models.StringList{"Maximinus Daia"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 305, ReignEnd: 313, SortOrder: 74, RarityTier: models.RarityTierScarce, Notes: "Also known as Maximinus Daia. Caesar 305-310, Augustus 310-313."},
		{Name: "Licinius", NormalizedName: "licinius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 308, ReignEnd: 324, SortOrder: 75, RarityTier: models.RarityTierCommon},
		{Name: "Licinius II", NormalizedName: "liciniusii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Tetrarchic/Diocletianic", ReignStart: 317, ReignEnd: 324, SortOrder: 76, RarityTier: models.RarityTierRare, Notes: "Son of Licinius, executed 325, never Augustus."},
		{Name: "Constantine I", NormalizedName: "constantinei", Aliases: models.StringList{"Constantine the Great"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 306, ReignEnd: 337, SortOrder: 77, RarityTier: models.RarityTierCommon, Notes: "Known as Constantine the Great. Sole ruler from 324."},
		{Name: "Crispus", NormalizedName: "crispus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 317, ReignEnd: 326, SortOrder: 78, RarityTier: models.RarityTierScarce, Notes: "Executed by his father; never Augustus."},
		{Name: "Constantine II", NormalizedName: "constantineii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 337, ReignEnd: 340, SortOrder: 79, RarityTier: models.RarityTierScarce, Notes: "Caesar 317-337, Augustus 337-340."},
		{Name: "Constantius II", NormalizedName: "constantiusii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 337, ReignEnd: 361, SortOrder: 80, RarityTier: models.RarityTierCommon, Notes: "Caesar 324-337, Augustus 337-361."},
		{Name: "Constans", NormalizedName: "constans", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 337, ReignEnd: 350, SortOrder: 81, RarityTier: models.RarityTierCommon, Notes: "Caesar 333-337, Augustus 337-350."},
		{Name: "Delmatius", NormalizedName: "delmatius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 335, ReignEnd: 337, SortOrder: 82, RarityTier: models.RarityTierVeryRare, Notes: "Executed 337; never Augustus."},
		{Name: "Hannibalianus", NormalizedName: "hannibalianus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleOther, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 335, ReignEnd: 337, SortOrder: 83, RarityTier: models.RarityTierVeryRare, Notes: "Held the special title 'King of Kings,' not standard Caesar rank; executed 337."},
		{Name: "Magnentius", NormalizedName: "magnentius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 350, ReignEnd: 353, SortOrder: 84, RarityTier: models.RarityTierScarce},
		{Name: "Vetranio", NormalizedName: "vetranio", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 350, ReignEnd: 350, SortOrder: 85, RarityTier: models.RarityTierRare, Notes: "Briefly proclaimed Augustus, abdicated same year."},
		{Name: "Nepotianus", NormalizedName: "nepotianus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 350, ReignEnd: 350, SortOrder: 86, RarityTier: models.RarityTierVeryRare, Notes: "Rome-based usurper, reigned ~4 weeks."},
		{Name: "Constantius Gallus", NormalizedName: "constantiusgallus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleCaesar, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 351, ReignEnd: 354, SortOrder: 87, RarityTier: models.RarityTierRare, Notes: "Executed; never Augustus."},
		{Name: "Julian", NormalizedName: "julian", Aliases: models.StringList{"Julian the Apostate"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 360, ReignEnd: 363, SortOrder: 88, RarityTier: models.RarityTierCommon, Notes: "Known as Julian the Apostate. Caesar 355-360, Augustus 360-363."},
		{Name: "Jovian", NormalizedName: "jovian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Constantinian", ReignStart: 363, ReignEnd: 364, SortOrder: 89, RarityTier: models.RarityTierScarce},
		{Name: "Valentinian I", NormalizedName: "valentiniani", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 364, ReignEnd: 375, SortOrder: 90, RarityTier: models.RarityTierCommon},
		{Name: "Valens", NormalizedName: "valens", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 364, ReignEnd: 378, SortOrder: 91, RarityTier: models.RarityTierCommon, Notes: "Ruled the eastern provinces, but tagged west per this dataset's pre-395 convention."},
		{Name: "Procopius", NormalizedName: "procopius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 365, ReignEnd: 366, SortOrder: 92, RarityTier: models.RarityTierRare, Notes: "Usurped against Valens in Constantinople."},
		{Name: "Gratian", NormalizedName: "gratian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 367, ReignEnd: 383, SortOrder: 93, RarityTier: models.RarityTierScarce, Notes: "Co-emperor from 367, senior from 375."},
		{Name: "Valentinian II", NormalizedName: "valentinianii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 375, ReignEnd: 392, SortOrder: 94, RarityTier: models.RarityTierScarce},
		{Name: "Magnus Maximus", NormalizedName: "magnusmaximus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 383, ReignEnd: 388, SortOrder: 95, RarityTier: models.RarityTierScarce, Notes: "Usurped against Gratian; briefly controlled Britain/Gaul/Spain."},
		{Name: "Eugenius", NormalizedName: "eugenius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Valentinianic", ReignStart: 392, ReignEnd: 394, SortOrder: 96, RarityTier: models.RarityTierRare, Notes: "Usurped against Valentinian II/Theodosius I."},
		{Name: "Theodosius I", NormalizedName: "theodosiusi", Aliases: models.StringList{"Theodosius the Great"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Theodosian (West)", ReignStart: 379, ReignEnd: 395, SortOrder: 97, RarityTier: models.RarityTierCommon, Notes: "Known as Theodosius the Great. Last sole ruler of the whole (still-unified) empire."},
		{Name: "Honorius", NormalizedName: "honorius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Theodosian (West)", ReignStart: 393, ReignEnd: 423, SortOrder: 98, RarityTier: models.RarityTierCommon},
		{Name: "Constantius III", NormalizedName: "constantiusiii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Theodosian (West)", ReignStart: 421, ReignEnd: 421, SortOrder: 99, RarityTier: models.RarityTierVeryRare, Notes: "Co-emperor for ~7 months; husband of Galla Placidia."},
		{Name: "Valentinian III", NormalizedName: "valentinianiii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Theodosian (West)", ReignStart: 425, ReignEnd: 455, SortOrder: 100, RarityTier: models.RarityTierScarce},
		{Name: "Petronius Maximus", NormalizedName: "petroniusmaximus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 455, ReignEnd: 455, SortOrder: 101, RarityTier: models.RarityTierVeryRare, Notes: "~3-month reign."},
		{Name: "Avitus", NormalizedName: "avitus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 455, ReignEnd: 456, SortOrder: 102, RarityTier: models.RarityTierRare},
		{Name: "Priscus Attalus", NormalizedName: "priscusattalus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 409, ReignEnd: 415, SortOrder: 103, RarityTier: models.RarityTierVeryRare, Notes: "Puppet emperor twice under Visigothic backing (409-410, 414-415)."},
		{Name: "Constantine III", NormalizedName: "constantineiii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 407, ReignEnd: 411, SortOrder: 104, RarityTier: models.RarityTierRare, Notes: "British usurper who crossed to Gaul/Spain."},
		{Name: "Jovinus", NormalizedName: "jovinus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 411, ReignEnd: 413, SortOrder: 105, RarityTier: models.RarityTierVeryRare, Notes: "Gallic usurper."},
		{Name: "Sebastianus", NormalizedName: "sebastianus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 412, ReignEnd: 413, SortOrder: 106, RarityTier: models.RarityTierVeryRare, Notes: "Co-usurper with Jovinus (his brother)."},
		{Name: "Maximus of Hispania", NormalizedName: "maximusofhispania", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 409, ReignEnd: 422, SortOrder: 107, RarityTier: models.RarityTierVeryRare, Notes: "Spanish usurper, two separate spells (409-411, 419-422)."},
		{Name: "Majorian", NormalizedName: "majorian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 457, ReignEnd: 461, SortOrder: 108, RarityTier: models.RarityTierScarce},
		{Name: "Libius Severus", NormalizedName: "libiusseverus", Aliases: models.StringList{"Severus III"}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 461, ReignEnd: 465, SortOrder: 109, RarityTier: models.RarityTierRare, Notes: "Also known as Severus III."},
		{Name: "Anthemius", NormalizedName: "anthemius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 467, ReignEnd: 472, SortOrder: 110, RarityTier: models.RarityTierScarce},
		{Name: "Olybrius", NormalizedName: "olybrius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 472, ReignEnd: 472, SortOrder: 111, RarityTier: models.RarityTierVeryRare, Notes: "~7-month reign."},
		{Name: "Glycerius", NormalizedName: "glycerius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 473, ReignEnd: 474, SortOrder: 112, RarityTier: models.RarityTierVeryRare},
		{Name: "Julius Nepos", NormalizedName: "juliusnepos", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 474, ReignEnd: 475, SortOrder: 113, RarityTier: models.RarityTierRare, Notes: "Continued to claim the title from Dalmatia until 480."},
		{Name: "Romulus Augustulus", NormalizedName: "romulusaugustulus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionWest, Dynasty: "Western collapse", ReignStart: 475, ReignEnd: 476, SortOrder: 114, RarityTier: models.RarityTierVeryRare, Notes: "Last Western emperor recognized in Italy; deposed by Odoacer."},
		{Name: "Arcadius", NormalizedName: "arcadius", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionEast, Dynasty: "Theodosian (East)", ReignStart: 395, ReignEnd: 408, SortOrder: 115, RarityTier: models.RarityTierCommon, Notes: "Co-emperor from 383, sole Eastern ruler from the 395 split."},
		{Name: "Theodosius II", NormalizedName: "theodosiusii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionEast, Dynasty: "Theodosian (East)", ReignStart: 408, ReignEnd: 450, SortOrder: 116, RarityTier: models.RarityTierCommon},
		{Name: "Marcian", NormalizedName: "marcian", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionEast, Dynasty: "Theodosian (East)", ReignStart: 450, ReignEnd: 457, SortOrder: 117, RarityTier: models.RarityTierScarce, Notes: "Married Pulcheria; not blood-Theodosian but conventionally grouped here."},
		{Name: "Leo I", NormalizedName: "leoi", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionEast, Dynasty: "Leonid", ReignStart: 457, ReignEnd: 474, SortOrder: 118, RarityTier: models.RarityTierCommon},
		{Name: "Leo II", NormalizedName: "leoii", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionEast, Dynasty: "Leonid", ReignStart: 473, ReignEnd: 474, SortOrder: 119, RarityTier: models.RarityTierVeryRare, Notes: "Co-emperor with grandfather Leo I, then sole for months."},
		{Name: "Zeno", NormalizedName: "zeno", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmperor, Region: models.ImperialFigureRegionEast, Dynasty: "Leonid", ReignStart: 474, ReignEnd: 491, SortOrder: 120, RarityTier: models.RarityTierScarce, Notes: "Included per explicit request -- reign began 474 (before cutoff), continued past 476 via restoration."},
		{Name: "Basiliscus", NormalizedName: "basiliscus", Aliases: models.StringList{}, Role: models.ImperialFigureRoleUsurper, Region: models.ImperialFigureRegionEast, Dynasty: "Leonid", ReignStart: 475, ReignEnd: 476, SortOrder: 121, RarityTier: models.RarityTierRare, Notes: "Deposed Zeno during his first reign."},
		{Name: "Livia", NormalizedName: "livia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: -27, ReignEnd: 14, SortOrder: 122, RarityTier: models.RarityTierCommon, Notes: "Wife of Augustus."},
		{Name: "Agrippina the Younger", NormalizedName: "agrippinatheyounger", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 41, ReignEnd: 68, SortOrder: 123, RarityTier: models.RarityTierScarce, Notes: "Wife of Claudius, mother of Nero."},
		{Name: "Poppaea Sabina", NormalizedName: "poppaeasabina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 54, ReignEnd: 68, SortOrder: 124, RarityTier: models.RarityTierRare, Notes: "Wife of Nero. Mostly provincial issues."},
		{Name: "Domitia", NormalizedName: "domitia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 81, ReignEnd: 96, SortOrder: 125, RarityTier: models.RarityTierScarce, Notes: "Wife of Domitian."},
		{Name: "Plotina", NormalizedName: "plotina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 98, ReignEnd: 117, SortOrder: 126, RarityTier: models.RarityTierScarce, Notes: "Wife of Trajan."},
		{Name: "Sabina", NormalizedName: "sabina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 117, ReignEnd: 138, SortOrder: 127, RarityTier: models.RarityTierScarce, Notes: "Wife of Hadrian."},
		{Name: "Faustina the Elder", NormalizedName: "faustinatheelder", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 138, ReignEnd: 161, SortOrder: 128, RarityTier: models.RarityTierCommon, Notes: "Wife of Antoninus Pius."},
		{Name: "Faustina the Younger", NormalizedName: "faustinatheyounger", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 161, ReignEnd: 180, SortOrder: 129, RarityTier: models.RarityTierCommon, Notes: "Wife of Marcus Aurelius."},
		{Name: "Lucilla", NormalizedName: "lucilla", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 161, ReignEnd: 169, SortOrder: 130, RarityTier: models.RarityTierScarce, Notes: "Wife of Lucius Verus."},
		{Name: "Crispina", NormalizedName: "crispina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 177, ReignEnd: 192, SortOrder: 131, RarityTier: models.RarityTierScarce, Notes: "Wife of Commodus."},
		{Name: "Julia Domna", NormalizedName: "juliadomna", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 193, ReignEnd: 211, SortOrder: 132, RarityTier: models.RarityTierCommon, Notes: "Wife of Septimius Severus."},
		{Name: "Plautilla", NormalizedName: "plautilla", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 202, ReignEnd: 205, SortOrder: 133, RarityTier: models.RarityTierScarce, Notes: "Wife of Caracalla."},
		{Name: "Julia Maesa", NormalizedName: "juliamaesa", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 218, ReignEnd: 225, SortOrder: 134, RarityTier: models.RarityTierScarce, Notes: "Grandmother of Elagabalus and Severus Alexander."},
		{Name: "Julia Soaemias", NormalizedName: "juliasoaemias", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 218, ReignEnd: 222, SortOrder: 135, RarityTier: models.RarityTierScarce, Notes: "Mother of Elagabalus."},
		{Name: "Julia Mamaea", NormalizedName: "juliamamaea", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 222, ReignEnd: 235, SortOrder: 136, RarityTier: models.RarityTierScarce, Notes: "Mother of Severus Alexander."},
		{Name: "Otacilia Severa", NormalizedName: "otaciliasevera", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 244, ReignEnd: 249, SortOrder: 137, RarityTier: models.RarityTierScarce, Notes: "Wife of Philip I."},
		{Name: "Herennia Etruscilla", NormalizedName: "herenniaetruscilla", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 249, ReignEnd: 251, SortOrder: 138, RarityTier: models.RarityTierScarce, Notes: "Wife of Trajan Decius."},
		{Name: "Salonina", NormalizedName: "salonina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 253, ReignEnd: 268, SortOrder: 139, RarityTier: models.RarityTierScarce, Notes: "Wife of Gallienus."},
		{Name: "Severina", NormalizedName: "severina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 274, ReignEnd: 275, SortOrder: 140, RarityTier: models.RarityTierRare, Notes: "Wife of Aurelian; possibly ruled briefly as regent, 275."},
		{Name: "Magnia Urbica", NormalizedName: "magniaurbica", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 283, ReignEnd: 285, SortOrder: 141, RarityTier: models.RarityTierRare, Notes: "Wife of Carinus."},
		{Name: "Galeria Valeria", NormalizedName: "galeriavaleria", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 293, ReignEnd: 311, SortOrder: 142, RarityTier: models.RarityTierRare, Notes: "Daughter of Diocletian, wife of Galerius."},
		{Name: "Helena", NormalizedName: "helena", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 306, ReignEnd: 330, SortOrder: 143, RarityTier: models.RarityTierScarce, Notes: "Mother of Constantine I."},
		{Name: "Fausta", NormalizedName: "fausta", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 307, ReignEnd: 326, SortOrder: 144, RarityTier: models.RarityTierRare, Notes: "Wife of Constantine I."},
		{Name: "Theodora", NormalizedName: "theodora", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 293, ReignEnd: 306, SortOrder: 145, RarityTier: models.RarityTierVeryRare, Notes: "Wife of Constantius Chlorus; coinage existence uncertain, needs verification."},
		{Name: "Aelia Flaccilla", NormalizedName: "aeliaflaccilla", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 379, ReignEnd: 386, SortOrder: 146, RarityTier: models.RarityTierRare, Notes: "Wife of Theodosius I."},
		{Name: "Eudoxia", NormalizedName: "eudoxia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionEast, Dynasty: "Empresses", ReignStart: 395, ReignEnd: 404, SortOrder: 147, RarityTier: models.RarityTierScarce, Notes: "Wife of Arcadius."},
		{Name: "Galla Placidia", NormalizedName: "gallaplacidia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 421, ReignEnd: 450, SortOrder: 148, RarityTier: models.RarityTierScarce, Notes: "Regent for Valentinian III."},
		{Name: "Pulcheria", NormalizedName: "pulcheria", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionEast, Dynasty: "Empresses", ReignStart: 414, ReignEnd: 453, SortOrder: 149, RarityTier: models.RarityTierScarce, Notes: "Augusta from 414, well before her later marriage to Marcian."},
		{Name: "Eudocia", NormalizedName: "eudocia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionEast, Dynasty: "Empresses", ReignStart: 423, ReignEnd: 460, SortOrder: 150, RarityTier: models.RarityTierScarce, Notes: "Wife of Theodosius II."},
		{Name: "Licinia Eudoxia", NormalizedName: "liciniaeudoxia", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionWest, Dynasty: "Empresses", ReignStart: 437, ReignEnd: 455, SortOrder: 151, RarityTier: models.RarityTierRare, Notes: "Wife of Valentinian III."},
		{Name: "Verina", NormalizedName: "verina", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionEast, Dynasty: "Empresses", ReignStart: 457, ReignEnd: 484, SortOrder: 152, RarityTier: models.RarityTierRare, Notes: "Wife of Leo I."},
		{Name: "Ariadne", NormalizedName: "ariadne", Aliases: models.StringList{}, Role: models.ImperialFigureRoleEmpress, Region: models.ImperialFigureRegionEast, Dynasty: "Empresses", ReignStart: 474, ReignEnd: 515, SortOrder: 153, RarityTier: models.RarityTierRare, Notes: "Wife of Zeno."},
	}

	return db.Transaction(func(tx *gorm.DB) error {
		for _, entry := range seed {
			var existing models.RomanImperialFigure
			err := tx.Where("normalized_name = ?", entry.NormalizedName).First(&existing).Error
			if err == nil {
				updates := map[string]interface{}{
					"name":        entry.Name,
					"aliases":     entry.Aliases,
					"role":        entry.Role,
					"region":      entry.Region,
					"dynasty":     entry.Dynasty,
					"reign_start": entry.ReignStart,
					"reign_end":   entry.ReignEnd,
					"sort_order":  entry.SortOrder,
					"rarity_tier": entry.RarityTier,
					"notes":       entry.Notes,
				}
				if err := tx.Model(&existing).Updates(updates).Error; err != nil {
					return err
				}
				continue
			}
			if err != gorm.ErrRecordNotFound {
				return err
			}
			if err := tx.Create(&entry).Error; err != nil {
				return err
			}
		}
		return tx.Save(&models.AppSetting{Key: romanImperialFigureSeedVersionKey, Value: currentRomanImperialFigureSeedVersion}).Error
	})
}
