import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import CoinLookupPage from '../CoinLookupPage.vue'
import { createCoin, createCoinReference, createIntakeDraft, lookupCoin, uploadImage } from '@/api/client'

const routerPush = vi.fn()
const routerBack = vi.fn()

vi.mock('vue-router', () => ({
  useRouter: () => ({
    push: routerPush,
    back: routerBack,
  }),
}))

vi.mock('@/api/client', () => ({
  lookupCoin: vi.fn(),
  createCoin: vi.fn(),
  createCoinReference: vi.fn(),
  createIntakeDraft: vi.fn(),
  uploadImage: vi.fn(),
}))

describe('CoinLookupPage', () => {
  beforeEach(() => {
    vi.mocked(lookupCoin).mockReset()
    vi.mocked(createCoin).mockReset()
    vi.mocked(createCoinReference).mockReset()
    vi.mocked(createIntakeDraft).mockReset()
    vi.mocked(uploadImage).mockReset()
    routerPush.mockReset()
    routerBack.mockReset()

    vi.stubGlobal('URL', {
      createObjectURL: vi.fn(() => 'blob:lookup-image'),
      revokeObjectURL: vi.fn(),
    })
  })

  it('saves lookup results only as wishlist coins', async () => {
    const file = new File(['obverse'], 'obverse.jpg', { type: 'image/jpeg' })
    vi.mocked(lookupCoin).mockResolvedValue({
      data: {
        extractedData: {
          confidence: 'medium',
          rawAnalysis: '{"ruler":"Trajan"}',
          coinFields: {
            ruler: 'Trajan',
            denomination: 'Denarius',
            era: 'ancient',
            material: 'Silver',
            category: 'Roman',
          },
        },
        numistaCandidates: [],
        prefilledDraft: {
          name: 'Trajan Denarius',
          ruler: 'Trajan',
          denomination: 'Denarius',
          era: 'ancient',
          material: 'Silver',
          category: 'Roman',
          obverseDescription: 'Laureate bust of Trajan right',
          reverseDescription: 'Victory standing left',
          notes: 'Well-preserved example',
        },
        candidateReferences: [
          {
            catalog: 'Numista',
            number: '12345',
            uri: 'https://en.numista.com/catalogue/pieces12345.html',
          },
        ],
      },
    } as Awaited<ReturnType<typeof lookupCoin>>)
    vi.mocked(createIntakeDraft).mockResolvedValue({
      data: {
        draftId: 7,
        status: 'drafted',
        coin: {
          name: 'Trajan Denarius from intake',
          ruler: 'Trajan',
          denomination: 'Denarius',
          era: 'ancient',
          material: 'Silver',
          category: 'Roman',
          obverseDescription: 'Laureate bust of Trajan right',
          reverseDescription: 'Victory standing left',
          notes: 'Generated by standard intake analysis',
        },
        confidenceSummary: { overall: 'medium', uncertainFields: [] },
        evidence: [],
        unresolvedFields: [],
        expiresAt: '2026-06-12T00:00:00Z',
      },
    } as Awaited<ReturnType<typeof createIntakeDraft>>)
    vi.mocked(createCoin).mockResolvedValue({ data: { id: 42 } } as Awaited<ReturnType<typeof createCoin>>)
    vi.mocked(uploadImage).mockResolvedValue({ data: {} } as Awaited<ReturnType<typeof uploadImage>>)
    vi.mocked(createCoinReference).mockResolvedValue({ data: {} } as Awaited<ReturnType<typeof createCoinReference>>)

    const wrapper = mount(CoinLookupPage, {
      global: {
        stubs: {
          CameraCaptureModal: true,
          Camera: true,
          Upload: true,
          Search: true,
          ArrowLeft: true,
          X: true,
          AlertCircle: true,
          ShieldCheck: true,
          ExternalLink: true,
          RotateCcw: true,
          Bookmark: true,
        },
      },
    })

    const input = wrapper.find('input[type="file"]')
    Object.defineProperty(input.element, 'files', {
      value: [file],
      configurable: true,
    })
    await input.trigger('change')

    await wrapper.find('.btn-submit').trigger('click')
    await flushPromises()

    // No NGC cert, so should show editable review form
    expect(wrapper.text()).toContain('Review Coin Details')
    expect(wrapper.find('input[type="text"]').exists()).toBe(true)
    expect(wrapper.text()).not.toContain('Add to Collection')
    expect(wrapper.text()).toContain('Save to Wishlist')

    expect(createIntakeDraft).toHaveBeenCalledWith([file])
    const nameInput = wrapper.find('input[type="text"]')
    expect((nameInput.element as HTMLInputElement).value).toBe('Trajan Denarius from intake')

    const actionButtons = wrapper.findAll('.result-actions button')
    expect(actionButtons).toHaveLength(3)
    await actionButtons[2]!.trigger('click')
    await flushPromises()

    expect(createCoin).toHaveBeenCalledWith(expect.objectContaining({
      name: 'Trajan Denarius from intake',
      category: 'Roman',
      material: 'Silver',
      era: 'ancient',
      obverseDescription: 'Laureate bust of Trajan right',
      reverseDescription: 'Victory standing left',
      notes: 'Generated by standard intake analysis',
      isWishlist: true,
    }))
    expect(uploadImage).toHaveBeenCalledWith(42, file, 'obverse', true, false)
    expect(createCoinReference).toHaveBeenCalledWith(42, {
      catalog: 'Numista',
      number: '12345',
      uri: 'https://en.numista.com/catalogue/pieces12345.html',
    })
    expect(routerPush).toHaveBeenCalledWith('/wishlist')
  })

  it('lets the user cancel results without saving', async () => {
    vi.mocked(lookupCoin).mockResolvedValue({
      data: {
        extractedData: {
          confidence: 'medium',
          rawAnalysis: 'uncertain',
        },
        numistaCandidates: [],
        prefilledDraft: {
          name: 'Possible drachm',
        },
      },
    } as Awaited<ReturnType<typeof lookupCoin>>)
    vi.mocked(createIntakeDraft).mockResolvedValue({
      data: {
        draftId: 8,
        status: 'drafted',
        coin: {
          name: 'Possible drachm',
          obverseDescription: 'Head right',
          reverseDescription: 'Figure standing',
        },
        confidenceSummary: { overall: 'low', uncertainFields: [] },
        evidence: [],
        unresolvedFields: [],
        expiresAt: '2026-06-12T00:00:00Z',
      },
    } as Awaited<ReturnType<typeof createIntakeDraft>>)

    const wrapper = mount(CoinLookupPage, {
      global: {
        stubs: {
          CameraCaptureModal: true,
          Camera: true,
          Upload: true,
          Search: true,
          ArrowLeft: true,
          X: true,
          AlertCircle: true,
          ShieldCheck: true,
          ExternalLink: true,
          RotateCcw: true,
          Bookmark: true,
        },
      },
    })

    const input = wrapper.find('input[type="file"]')
    Object.defineProperty(input.element, 'files', {
      value: [new File(['coin'], 'coin.jpg', { type: 'image/jpeg' })],
      configurable: true,
    })
    await input.trigger('change')

    await wrapper.find('.btn-submit').trigger('click')
    await flushPromises()

    const cancel = wrapper.findAll('button').find(button => button.text().includes('Cancel'))
    expect(cancel).toBeDefined()
    await cancel?.trigger('click')

    expect(createCoin).not.toHaveBeenCalled()
    expect(routerBack).toHaveBeenCalled()
  })

  it('shows read-only details when NGC cert is detected', async () => {
    const file = new File(['slab'], 'slab.jpg', { type: 'image/jpeg' })
    vi.mocked(lookupCoin).mockResolvedValue({
      data: {
        extractedData: {
          confidence: 'high',
          rawAnalysis: 'NGC cert detected',
          ngc: {
            certNumber: '1234567-001',
            normalizedCert: '1234567001',
            lookupURL: 'https://www.ngccoin.com/certlookup/1234567001/NGCAncients/',
            grade: 'Ch VF',
            description: 'Augustus Denarius',
          },
        },
        numistaCandidates: [],
        prefilledDraft: {
          name: 'Augustus Denarius',
          ruler: 'Augustus',
          denomination: 'Denarius',
          era: 'ancient',
          material: 'Silver',
          category: 'Roman',
          grade: 'Ch VF',
        },
      },
    } as Awaited<ReturnType<typeof lookupCoin>>)
    vi.mocked(createCoin).mockResolvedValue({ data: { id: 99 } } as Awaited<ReturnType<typeof createCoin>>)
    vi.mocked(uploadImage).mockResolvedValue({ data: {} } as Awaited<ReturnType<typeof uploadImage>>)

    const wrapper = mount(CoinLookupPage, {
      global: {
        stubs: {
          CameraCaptureModal: true,
          Camera: true,
          Upload: true,
          Search: true,
          ArrowLeft: true,
          X: true,
          AlertCircle: true,
          ShieldCheck: true,
          ExternalLink: true,
          RotateCcw: true,
          Bookmark: true,
        },
      },
    })

    const input = wrapper.find('input[type="file"]')
    Object.defineProperty(input.element, 'files', {
      value: [file],
      configurable: true,
    })
    await input.trigger('change')

    await wrapper.find('.btn-submit').trigger('click')
    await flushPromises()

    // NGC path should show read-only display
    expect(wrapper.text()).toContain('Extracted Details')
    expect(wrapper.text()).toContain('NGC Certification: 1234567001')
    expect(wrapper.text()).toContain('Verify on NGC')

    // Should NOT show editable form
    expect(wrapper.text()).not.toContain('Review Coin Details')
    expect(wrapper.findAll('input[type="text"]')).toHaveLength(0)
    expect(createIntakeDraft).not.toHaveBeenCalled()
  })
})
