package main

import (
	"github.com/briandenicola/ancient-coins-api/database"
	"github.com/briandenicola/ancient-coins-api/handlers"
	"github.com/briandenicola/ancient-coins-api/middleware"
	"github.com/briandenicola/ancient-coins-api/repository"
	"github.com/briandenicola/ancient-coins-api/services"
	"github.com/gin-gonic/gin"
)

// registerProtectedRoutes registers every endpoint that requires an
// authenticated user, via either a JWT bearer token or an API key.
func registerProtectedRoutes(api *gin.RouterGroup, d *appDeps) {
	protected := api.Group("")
	protected.Use(middleware.AuthRequiredWithSecurity(d.cfg.JWTSecret, d.apiKeyAuth, d.securitySvc))
	protected.Use(d.apiRateLimit)
	{
		coinReferenceRepo := repository.NewCoinReferenceRepository(database.DB)
		storageLocationRepo := repository.NewStorageLocationRepository(database.DB)
		mintLocationRepo := repository.NewMintLocationRepository(database.DB)
		catalogRegistryRepo := repository.NewCatalogRegistryRepository(database.DB)
		intakeDraftRepo := repository.NewCoinIntakeDraftRepository(database.DB)
		quickCaptureRepo := repository.NewQuickCaptureRepository(database.DB)
		coinReferenceSvc := services.NewCoinReferenceService(coinReferenceRepo, catalogRegistryRepo)
		referenceMigrationSvc := services.NewReferenceMigrationService(database.DB, coinReferenceRepo, catalogRegistryRepo, d.journalRepo)
		catalogRegistrySvc := services.NewCatalogRegistryService(catalogRegistryRepo)
		catalogRegistryHandler := handlers.NewCatalogRegistryHandler(catalogRegistrySvc)
		coinSvc := services.NewCoinService(d.coinRepo, d.notifSvc).WithReferenceSupport(coinReferenceRepo, coinReferenceSvc).WithStorageLocationSupport(storageLocationRepo).WithMintLocationSupport(mintLocationRepo).WithCatalogRegistrySupport(catalogRegistryRepo).WithSettingsSupport(d.settingsSvc)
		coinSvc.WithReminderSupport(d.purchaseReminderRepo)
		shipmentHandler := handlers.NewShipmentHandler(d.shipmentSvc)
		d.wishlistSearchAlertSvc.WithCoinCreation(coinSvc)
		coinHandler := handlers.NewCoinHandler(d.coinRepo, coinSvc, d.logger).WithSettingsSupport(d.settingsSvc).WithShipmentSupport(d.shipmentSvc)
		coinReferenceHandler := handlers.NewCoinReferenceHandler(coinReferenceRepo, coinReferenceSvc, referenceMigrationSvc)
		coinIntakeSvc := services.NewCoinIntakeService(intakeDraftRepo, d.coinRepo, d.agentProxy, d.settingsSvc)
		coinIntakeHandler := handlers.NewCoinIntakeHandler(coinIntakeSvc, d.logger)
		quickCaptureSvc := services.NewQuickCaptureService(quickCaptureRepo, d.cfg.UploadDir).
			WithCoinValidation(coinSvc).
			WithReferenceValidation(coinReferenceSvc)
		quickCaptureHandler := handlers.NewQuickCaptureHandler(quickCaptureSvc, d.logger)
		coinLookupHandler := handlers.NewCoinLookupHandler(d.coinLookupSvc, d.logger)
		protected.GET("/coins", coinHandler.List)
		protected.GET("/coins/:id", coinHandler.Get)
		protected.POST("/coins", coinHandler.Create)
		protected.POST("/coins/:id/duplicate", d.writeRateLimit, coinHandler.Duplicate)
		protected.POST("/coins/match-category-era", coinHandler.MatchCategoryEra)
		protected.POST("/coins/intake/draft", d.writeRateLimit, coinIntakeHandler.CreateDraft)
		protected.POST("/coins/intake/commit", d.writeRateLimit, coinIntakeHandler.CommitDraft)
		protected.GET("/quick-capture/drafts", quickCaptureHandler.ListDrafts)
		protected.POST("/quick-capture/drafts", d.writeRateLimit, quickCaptureHandler.CreateDraft)
		protected.GET("/quick-capture/drafts/:id", quickCaptureHandler.GetDraft)
		protected.PUT("/quick-capture/drafts/:id", d.writeRateLimit, quickCaptureHandler.UpdateDraft)
		protected.POST("/quick-capture/drafts/:id/discard", d.writeRateLimit, quickCaptureHandler.DiscardDraft)
		protected.POST("/quick-capture/drafts/:id/promote", d.writeRateLimit, quickCaptureHandler.PromoteDraft)
		protected.POST("/coins/lookup", d.writeRateLimit, coinLookupHandler.Lookup)
		protected.PUT("/coins/:id", coinHandler.Update)
		protected.GET("/coins/:id/references", coinReferenceHandler.List)
		protected.POST("/coins/:id/references", coinReferenceHandler.Create)
		protected.PUT("/coins/:id/references/:referenceId", coinReferenceHandler.Update)
		protected.DELETE("/coins/:id/references/:referenceId", coinReferenceHandler.Delete)
		protected.POST("/references/migrate-legacy", coinReferenceHandler.MigrateLegacy)
		protected.POST("/coins/:id/purchase", coinHandler.Purchase)
		protected.POST("/coins/:id/sell", coinHandler.Sell)
		protected.GET("/coins/:id/shipment", shipmentHandler.GetForCoin)
		protected.PUT("/coins/:id/shipment", shipmentHandler.UpsertForCoin)
		protected.DELETE("/coins/:id/shipment", shipmentHandler.DeleteForCoin)
		protected.PUT("/coins/:id/shipment/manual-override", shipmentHandler.SetManualOverride)
		protected.POST("/coins/:id/shipment/sync", shipmentHandler.SyncForCoin)
		protected.DELETE("/coins/:id", coinHandler.Delete)
		protected.GET("/catalogs", catalogRegistryHandler.List)

		purchaseReminderHandler := handlers.NewPurchaseReminderHandler(d.purchaseReminderSvc, d.logger)
		protected.POST("/coins/:id/reminder", purchaseReminderHandler.CreateOrUpdate)
		protected.GET("/coins/:id/reminder", purchaseReminderHandler.Get)
		protected.DELETE("/coins/:id/reminder", purchaseReminderHandler.Cancel)
		protected.GET("/purchase-reminders", purchaseReminderHandler.List)

		noteSvc := services.NewNoteService(d.noteRepo)
		noteHandler := handlers.NewNoteHandler(noteSvc)
		protected.GET("/notes", noteHandler.List)
		protected.POST("/notes", noteHandler.Create)
		protected.GET("/notes/:id", noteHandler.Get)
		protected.PUT("/notes/:id", noteHandler.Update)
		protected.DELETE("/notes/:id", noteHandler.Delete)

		storageLocationSvc := services.NewStorageLocationService(storageLocationRepo)
		storageLocationHandler := handlers.NewStorageLocationHandler(storageLocationSvc)
		protected.GET("/storage-locations", storageLocationHandler.List)
		protected.POST("/storage-locations", storageLocationHandler.Create)
		protected.PUT("/storage-locations/:id", storageLocationHandler.Update)
		protected.DELETE("/storage-locations/:id", storageLocationHandler.Delete)
		mintLocationSvc := services.NewMintLocationService(mintLocationRepo)
		geocodeSvc := services.NewGeocodeService()
		mintLocationHandler := handlers.NewMintLocationHandler(mintLocationSvc).WithGeocoding(geocodeSvc)
		protected.GET("/mint-locations", mintLocationHandler.List)
		protected.GET("/mint-locations/geocode", mintLocationHandler.Geocode)
		protected.POST("/mint-locations", mintLocationHandler.CreatePrivate)
		protected.PUT("/mint-locations/:id", mintLocationHandler.UpdatePrivate)
		protected.DELETE("/mint-locations/:id", mintLocationHandler.DeletePrivate)

		romanImperialFigureRepo := repository.NewRomanImperialFigureRepository(database.DB)
		romanImperialFigureSvc := services.NewRomanImperialFigureService(romanImperialFigureRepo)
		romanImperialFigureHandler := handlers.NewRomanImperialFigureHandler(romanImperialFigureSvc)
		protected.GET("/roman-imperial-figures", romanImperialFigureHandler.Search)
		protected.GET("/roman-imperial-figures/:id", romanImperialFigureHandler.Get)

		emperorTrackerUserRepo := repository.NewUserRepository(database.DB)
		emperorTrackerHighlightRepo := repository.NewRomanImperialFigureHighlightRepository(database.DB)
		emperorTrackerSvc := services.NewEmperorTrackerService(romanImperialFigureRepo, d.coinRepo, emperorTrackerHighlightRepo)
		emperorTrackerHandler := handlers.NewEmperorTrackerHandler(emperorTrackerSvc, emperorTrackerUserRepo)
		protected.GET("/stats/emperors", emperorTrackerHandler.GetProgress)
		protected.PUT("/stats/emperors/highlights/:figureId", emperorTrackerHandler.SetHighlight)

		tagRepo := repository.NewTagRepository(database.DB)
		tagHandler := handlers.NewTagHandler(tagRepo)
		setRepo := repository.NewSetRepository(database.DB)
		recommendationRepo := repository.NewCoinRecommendationRepository(database.DB)
		recommendationService := services.NewCoinRecommendationService(recommendationRepo, tagRepo, setRepo)
		recommendationHandler := handlers.NewCoinRecommendationHandler(recommendationService)
		protected.GET("/tags", tagHandler.List)
		protected.POST("/tags", tagHandler.Create)
		protected.PUT("/tags/:id", tagHandler.Update)
		protected.DELETE("/tags/:id", tagHandler.Delete)
		bulkHandler := handlers.NewBulkHandler(d.coinRepo, tagRepo, storageLocationRepo, setRepo)
		protected.POST("/coins/bulk", bulkHandler.BulkAction)

		protected.POST("/coins/:id/tags", tagHandler.AttachToCoin)
		protected.DELETE("/coins/:id/tags/:tagId", tagHandler.DetachFromCoin)
		protected.GET("/coins/:id/recommendations", recommendationHandler.List)
		protected.POST("/coins/:id/recommendations/:recommendationId/accept", recommendationHandler.Accept)
		protected.POST("/coins/:id/recommendations/:recommendationId/reject", recommendationHandler.Reject)

		// Sets - new endpoints for coin sets
		setService := services.NewSetService(setRepo, tagRepo, d.notifRepo)
		setHandler := handlers.NewSetHandler(setRepo, setService).WithSettingsSupport(d.settingsSvc)
		setBuilderRepo := repository.NewSetBuilderRepository(database.DB)
		setBuilderService := services.NewSetBuilderService(setBuilderRepo, d.notifRepo).
			WithWorkflow(d.agentProxy, d.settingsSvc, repository.NewAgentRepository(database.DB), d.logger).
			WithSetRepository(setRepo)
		setBuilderService.StartWorkers(1)
		setBuilderHandler := handlers.NewSetBuilderHandler(setBuilderService)
		setSnapshotScheduler := services.NewSetSnapshotScheduler(setService, d.settingsSvc, d.logger)
		go setSnapshotScheduler.Start()
		protected.GET("/sets", setHandler.List)
		protected.GET("/sets/templates", setHandler.GetTemplates)
		protected.GET("/sets/suggested-criteria", setHandler.GetSuggestedCriteria)
		protected.GET("/sets/criteria-templates", setHandler.ListCriteriaTemplates)
		protected.POST("/sets/criteria-templates", setHandler.SaveCriteriaTemplate)
		protected.DELETE("/sets/criteria-templates/:id", setHandler.DeleteCriteriaTemplate)
		protected.POST("/sets/import-csv", setHandler.CreateFromCSV)
		protected.POST("/sets/compare", setHandler.CompareSets)
		protected.POST("/sets/preview-smart", setHandler.PreviewSmartSet)
		protected.POST("/sets", setHandler.Create)
		protected.GET("/sets/:id", setHandler.Get)
		protected.PUT("/sets/:id", setHandler.Update)
		protected.DELETE("/sets/:id", setHandler.Delete)
		protected.GET("/sets/:id/coins", setHandler.GetCoins)
		protected.POST("/sets/:id/coins", setHandler.AddCoin)
		protected.PUT("/sets/:id/coins/order", setHandler.ReorderCoins)
		protected.DELETE("/sets/:id/coins/:coinId", setHandler.RemoveCoin)
		protected.GET("/sets/:id/completion", setHandler.GetCompletion)
		protected.POST("/sets/:id/snapshot", setHandler.CreateSnapshot)
		protected.GET("/sets/:id/trends", setHandler.GetTrends)
		protected.GET("/sets/:id/analytics", setHandler.GetAnalytics)
		protected.POST("/set-builder/runs", setBuilderHandler.CreateRun)
		protected.GET("/set-builder/proposals", setBuilderHandler.ListProposals)
		protected.GET("/set-builder/proposals/:id", setBuilderHandler.GetProposal)
		protected.PUT("/set-builder/proposals/:id", setBuilderHandler.UpdateProposal)
		protected.POST("/set-builder/proposals/:id/approve", setBuilderHandler.ApproveProposal)
		protected.POST("/set-builder/proposals/:id/reject", setBuilderHandler.RejectProposal)
		protected.POST("/set-builder/proposals/:id/regenerate", setBuilderHandler.RegenerateProposal)

		journalHandler := handlers.NewJournalHandler(d.journalRepo)
		protected.GET("/coins/:id/journal", journalHandler.ListEntries)
		protected.POST("/coins/:id/journal", journalHandler.AddEntry)
		protected.DELETE("/coins/:id/journal/:entryId", journalHandler.DeleteEntry)

		protected.GET("/stats", coinHandler.Stats)
		healthHandler := handlers.NewHealthHandler(d.healthSvc, d.logger)
		protected.GET("/stats/health", healthHandler.CollectionSummary)
		protected.GET("/coins/health", healthHandler.ListCoinHealth)
		protected.GET("/coins/:id/health", healthHandler.GetCoinHealth)
		timeMachineHandler := handlers.NewTimeMachineHandler(d.timeMachineSvc)
		protected.GET("/stats/time-machine", timeMachineHandler.GetSnapshot)
		protected.GET("/stats/time-machine/bounds", timeMachineHandler.GetBounds)
		protected.GET("/stats/distribution", coinHandler.Distribution)
		protected.GET("/stats/investment-breakdown", coinHandler.InvestmentBreakdown)
		protected.GET("/value-history", coinHandler.ValueHistory)
		protected.GET("/coins/:id/value-history", coinHandler.CoinValueHistory)
		protected.GET("/suggestions", coinHandler.Suggestions)

		protected.POST("/coins/:id/images", d.writeRateLimit, d.imageHandler.Upload)
		protected.POST("/coins/:id/images/base64", d.writeRateLimit, d.imageHandler.UploadBase64)
		protected.DELETE("/coins/:id/images/:imageId", d.imageHandler.Delete)
		protected.GET("/uploads/*filepath", d.imageHandler.ServeUpload)
		protected.GET("/proxy-image", d.imageHandler.ProxyImage)
		protected.GET("/scrape-image", d.imageHandler.ScrapeImage)

		analysisRepo := repository.NewAnalysisRepository(database.DB)
		analysisHandler := handlers.NewAnalysisHandler(analysisRepo, d.agentProxy, d.settingsSvc, d.logger)
		aiJobHandler := handlers.NewAIJobHandler(d.aiJobSvc, d.logger)
		protected.POST("/coins/:id/analyze", d.writeRateLimit, aiJobHandler.Analyze)
		protected.POST("/coins/:id/grade", d.writeRateLimit, aiJobHandler.Grade)
		protected.DELETE("/coins/:id/analyze", analysisHandler.DeleteAnalysis)
		protected.GET("/ai-jobs/:id", aiJobHandler.GetJob)
		protected.GET("/coins/:id/ai-jobs", aiJobHandler.ListCoinJobs)
		protected.POST("/extract-text", analysisHandler.ExtractText)
		protected.GET("/ollama-status", analysisHandler.OllamaStatus)
		protected.GET("/ai-status", analysisHandler.AIStatus)

		deepIdentificationProposalSvc := services.NewDeepIdentificationProposalService(d.deepIdentificationRepo, d.coinRepo, coinSvc, quickCaptureSvc, coinReferenceSvc).WithLogger(d.logger)
		deepIdentificationHandler := handlers.NewDeepIdentificationHandler(d.deepIdentificationSvc, d.settingsSvc, d.logger).WithProposalSupport(deepIdentificationProposalSvc)
		protected.GET("/deep-identification/capability", deepIdentificationHandler.Capability)
		protected.POST("/deep-identification/jobs", d.writeRateLimit, deepIdentificationHandler.CreateJob)
		protected.GET("/deep-identification/jobs", deepIdentificationHandler.ListJobs)
		protected.GET("/deep-identification/jobs/:id", deepIdentificationHandler.GetJob)
		protected.DELETE("/deep-identification/jobs/:id", d.writeRateLimit, deepIdentificationHandler.DeleteJob)
		protected.GET("/deep-identification/jobs/:id/events", deepIdentificationHandler.StreamEvents)
		protected.POST("/deep-identification/jobs/:id/cancel", d.writeRateLimit, deepIdentificationHandler.Cancel)
		protected.POST("/deep-identification/jobs/:id/retry", d.writeRateLimit, deepIdentificationHandler.Retry)
		protected.PATCH("/deep-identification/jobs/:id/proposal", d.writeRateLimit, deepIdentificationHandler.UpdateProposal)
		protected.POST("/deep-identification/jobs/:id/apply", d.writeRateLimit, deepIdentificationHandler.ApplyProposal)

		// Coin of the Day (user-facing)
		coinOfDayHandler := handlers.NewCoinOfDayHandler(d.featuredCoinRepo, d.logger)
		protected.GET("/featured-coins/latest", coinOfDayHandler.Latest)
		protected.GET("/featured-coins/:id", coinOfDayHandler.Get)

		numistaHandler := handlers.NewNumistaHandler(d.numistaLookupSvc)
		protected.POST("/numista/query-proposal", numistaHandler.QueryProposal)
		protected.POST("/numista/lookup", numistaHandler.Lookup)
		protected.POST("/numista/enrich", numistaHandler.Enrich)
		protected.GET("/numista/search", numistaHandler.Search)

		auctionLotSvc := services.NewAuctionLotService(d.auctionLotRepo, d.coinRepo).
			WithImageService(d.imageSvc).
			WithMarketSignal(d.agentProxy, d.settingsSvc)
		nbSvc := services.NewNumisBidsService(d.logger)
		cngSvc := services.NewCNGAuctionService(d.logger)
		auctionUserRepo := repository.NewUserRepository(database.DB)
		auctionLotHandler := handlers.NewAuctionLotHandler(d.auctionLotRepo, auctionLotSvc, auctionUserRepo, nbSvc, cngSvc, d.logger, d.credentialEncryptionSvc).WithShipmentSupport(d.shipmentSvc)
		protected.GET("/auctions", auctionLotHandler.List)
		protected.GET("/auctions/counts", auctionLotHandler.Counts)
		protected.PUT("/auctions/bulk-link-event", auctionLotHandler.BulkLinkEvent)
		protected.GET("/auctions/:id", auctionLotHandler.Get)
		protected.POST("/auctions", auctionLotHandler.Create)
		protected.PUT("/auctions/:id", auctionLotHandler.Update)
		protected.PUT("/auctions/:id/status", auctionLotHandler.UpdateStatus)
		protected.PUT("/auctions/:id/event", auctionLotHandler.LinkEvent)
		protected.POST("/auctions/:id/convert", auctionLotHandler.ConvertToCoin)
		protected.GET("/auctions/:id/bid-recommendation", auctionLotHandler.GetBidRecommendation)
		protected.POST("/auctions/:id/market-signal", d.writeRateLimit, auctionLotHandler.GetMarketSignal)
		protected.DELETE("/auctions/:id", auctionLotHandler.Delete)
		protected.POST("/auctions/import", d.writeRateLimit, auctionLotHandler.ImportFromURL)
		protected.POST("/auctions/sync", d.writeRateLimit, auctionLotHandler.SyncWatchlist)
		protected.POST("/auctions/validate-credentials", auctionLotHandler.ValidateNumisBids)

		// Wishlist availability checking
		availHandler := handlers.NewAvailabilityHandler(d.availSvc, d.availScheduler, d.availRepo, d.coinRepo).WithCycleRepo(d.availCycleRepo)
		protected.POST("/wishlist/check-availability", availHandler.CheckAvailability)
		protected.PUT("/coins/:id/listing-status", availHandler.UpdateListingStatus)
		protected.GET("/wishlist/availability-runs", availHandler.ListOwnerRuns)
		protected.GET("/wishlist/availability-runs/:id", availHandler.GetOwnerRunDetail)
		wishlistSearchAlertHandler := handlers.NewWishlistSearchAlertHandler(d.wishlistSearchAlertSvc)
		protected.GET("/wishlist/search-alerts", wishlistSearchAlertHandler.List)
		protected.POST("/wishlist/search-alerts", d.writeRateLimit, wishlistSearchAlertHandler.Create)
		protected.GET("/wishlist/search-alerts/:alertId", wishlistSearchAlertHandler.Get)
		protected.PUT("/wishlist/search-alerts/:alertId", d.writeRateLimit, wishlistSearchAlertHandler.Update)
		protected.DELETE("/wishlist/search-alerts/:alertId", d.writeRateLimit, wishlistSearchAlertHandler.Delete)
		protected.POST("/wishlist/search-alerts/:alertId/run", d.writeRateLimit, wishlistSearchAlertHandler.RunNow)
		protected.GET("/wishlist/search-alerts/:alertId/runs", wishlistSearchAlertHandler.ListRuns)
		protected.GET("/wishlist/search-alerts/:alertId/runs/:runId", wishlistSearchAlertHandler.GetRun)
		protected.GET("/wishlist/search-alerts/:alertId/candidates", wishlistSearchAlertHandler.ListCandidates)
		protected.POST("/wishlist/search-alerts/:alertId/candidates/:candidateId/dismiss", d.writeRateLimit, wishlistSearchAlertHandler.DismissCandidate)
		protected.POST("/wishlist/search-alerts/:alertId/candidates/:candidateId/restore", d.writeRateLimit, wishlistSearchAlertHandler.RestoreCandidate)
		protected.POST("/wishlist/search-alerts/:alertId/candidates/:candidateId/convert", d.writeRateLimit, wishlistSearchAlertHandler.ConvertCandidate)
		protected.POST("/wishlist/search-alerts/:alertId/criteria-adjustments", d.writeRateLimit, wishlistSearchAlertHandler.AdjustCriteria)

		agentRepo := repository.NewAgentRepository(database.DB)
		userRepo := repository.NewUserRepository(database.DB)
		contentGuard := services.NewContentGuard(d.logger)
		agentHandler := handlers.NewAgentHandler(agentRepo, userRepo, d.journalRepo, d.agentProxy, d.collectionSvc, d.settingsSvc, d.internalTokenSvc, contentGuard, d.logger, d.cfg.AgentInternalCallbackURL)
		protected.POST("/agent/chat", d.writeRateLimit, agentHandler.ChatStream)
		protected.POST("/agent/collection/proposals/:proposalId/commit", d.writeRateLimit, agentHandler.CommitCollectionProposal)
		protected.POST("/agent/collection/proposals/:proposalId/cancel", d.writeRateLimit, agentHandler.CancelCollectionProposal)
		protected.POST("/coins/:id/estimate-value", d.writeRateLimit, aiJobHandler.EstimateValue)
		protected.GET("/agent/models", agentHandler.ListModels)
		protected.GET("/agent/coin-search-prompt", agentHandler.GetCoinSearchPrompt)
		protected.GET("/agent/coin-shows-prompt", agentHandler.GetCoinShowsPrompt)
		protected.GET("/agent/valuation-prompt", agentHandler.GetValuationPrompt)
		protected.GET("/agent/portfolio-summary", agentHandler.PortfolioSummary)
		protected.GET("/agent/status", agentHandler.AgentStatus)

		conversationRepo := repository.NewConversationRepository(database.DB)
		convHandler := handlers.NewConversationHandler(conversationRepo)
		protected.GET("/agent/conversations", convHandler.List)
		protected.GET("/agent/conversations/:id", convHandler.Get)
		protected.POST("/agent/conversations", convHandler.Save)
		protected.DELETE("/agent/conversations/:id", convHandler.Delete)

		// User self-service routes
		userHandler := handlers.NewUserHandler(d.cfg.UploadDir, userRepo, d.pushoverSvc, d.logger, d.credentialEncryptionSvc)
		oidcUserHandler := handlers.NewOIDCHandler(d.oidcSvc)
		protected.GET("/auth/me", userHandler.GetMe)
		protected.POST("/auth/change-password", userHandler.ChangePassword)
		protected.POST("/auth/oidc/:providerId/link/start", oidcUserHandler.StartLink)
		protected.PUT("/user/profile", userHandler.UpdateProfile)
		protected.POST("/user/avatar", userHandler.UploadAvatar)
		protected.DELETE("/user/avatar", userHandler.DeleteAvatar)
		protected.GET("/user/oidc-identities", oidcUserHandler.ListLinkedIdentities)
		protected.DELETE("/user/oidc-identities/:identityId", oidcUserHandler.UnlinkIdentity)
		protected.GET("/user/export", userHandler.ExportCollection)
		protected.GET("/user/export/catalog", userHandler.ExportCatalogPDF)
		protected.POST("/user/import", d.writeRateLimit, userHandler.ImportCollection)
		protected.POST("/notifications/test-pushover", userHandler.TestPushover)

		// Social routes
		socialSvc := services.NewSocialService(d.socialRepo, d.notifSvc)
		socialHandler := handlers.NewSocialHandler(d.socialRepo, socialSvc, d.logger)
		protected.POST("/social/follow/:userId", socialHandler.FollowUser)
		protected.DELETE("/social/follow/:userId", socialHandler.UnfollowUser)
		protected.PUT("/social/followers/:userId/accept", socialHandler.AcceptFollower)
		protected.PUT("/social/followers/:userId/block", socialHandler.BlockFollower)
		protected.DELETE("/social/followers/:userId/block", socialHandler.UnblockFollower)
		protected.GET("/social/followers", socialHandler.GetFollowers)
		protected.GET("/social/following", socialHandler.GetFollowing)
		protected.GET("/social/blocked", socialHandler.GetBlockedUsers)
		protected.GET("/social/following/:userId/coins", socialHandler.GetFollowingCoins)
		protected.GET("/social/following/:userId/coins/:coinId", socialHandler.GetFollowingCoinDetail)
		protected.GET("/users/search", socialHandler.SearchUsers)
		protected.GET("/users/:username", socialHandler.GetPublicProfile)
		protected.POST("/social/coins/:coinId/comments", socialHandler.AddComment)
		protected.GET("/social/coins/:coinId/comments", socialHandler.GetComments)
		protected.DELETE("/social/coins/:coinId/comments/:commentId", socialHandler.DeleteComment)
		protected.PUT("/social/coins/:coinId/rating", socialHandler.RateCoin)
		protected.GET("/social/coins/:coinId/rating", socialHandler.GetCoinRating)

		// Notification routes
		notifHandler := handlers.NewNotificationHandler(d.notifRepo)
		protected.GET("/notifications", notifHandler.List)
		protected.GET("/notifications/unread-count", notifHandler.UnreadCount)
		protected.PUT("/notifications/:id/read", notifHandler.MarkRead)
		protected.PUT("/notifications/read-all", notifHandler.MarkAllRead)
		protected.DELETE("/notifications/:id", notifHandler.Delete)

		// API key management
		apiKeyHandler := handlers.NewApiKeyHandler(d.apiKeyRepo, d.logger, d.cfg.JWTSecret)
		protected.POST("/auth/api-keys", apiKeyHandler.Generate)
		protected.GET("/auth/api-keys", apiKeyHandler.List)
		protected.DELETE("/auth/api-keys/:id", apiKeyHandler.Revoke)

		// WebAuthn registration (requires auth)
		protected.POST("/auth/webauthn/register/begin", d.webauthnHandler.RegisterBegin)
		protected.POST("/auth/webauthn/register/finish", d.webauthnHandler.RegisterFinish)
		protected.GET("/auth/webauthn/credentials", d.webauthnHandler.ListCredentials)
		protected.DELETE("/auth/webauthn/credentials/:id", d.webauthnHandler.DeleteCredential)

		// Showcase routes
		showcaseRepo := repository.NewShowcaseRepository(database.DB)
		showcaseHandler := handlers.NewShowcaseHandler(showcaseRepo)
		protected.GET("/showcases", showcaseHandler.ListShowcases)
		protected.GET("/showcases/:id", showcaseHandler.GetShowcase)
		protected.POST("/showcases", showcaseHandler.CreateShowcase)
		protected.PUT("/showcases/:id", showcaseHandler.UpdateShowcase)
		protected.DELETE("/showcases/:id", showcaseHandler.DeleteShowcase)
		protected.PUT("/showcases/:id/coins", showcaseHandler.SetShowcaseCoins)

		// Calendar / Auction Event routes
		eventRepo := repository.NewAuctionEventRepository(database.DB)
		calendarHandler := handlers.NewCalendarHandler(eventRepo, d.auctionLotRepo)
		protected.GET("/calendar", calendarHandler.GetCalendar)
		protected.GET("/calendar/events", calendarHandler.ListEvents)
		protected.GET("/calendar/events/:id", calendarHandler.GetEvent)
		protected.POST("/calendar/events", calendarHandler.CreateEvent)
		protected.PUT("/calendar/events/:id", calendarHandler.UpdateEvent)
		protected.DELETE("/calendar/events/:id", calendarHandler.DeleteEvent)

		// Price Alerts & Bid Reminders
		alertSvc := services.NewAuctionAlertService(d.priceAlertRepo, d.bidReminderRepo, d.auctionLotRepo)
		alertHandler := handlers.NewAlertHandler(alertSvc)
		protected.GET("/alerts", alertHandler.ListAlerts)
		protected.POST("/alerts", alertHandler.CreateAlert)
		protected.DELETE("/alerts/:id", alertHandler.DeleteAlert)
		protected.GET("/reminders", alertHandler.ListReminders)
		protected.POST("/reminders", alertHandler.CreateReminder)
		protected.DELETE("/reminders/:id", alertHandler.DeleteReminder)
	}
}
